# -*- coding: utf-8 -*-
import os
import shutil
import subprocess
import json
import threading
from pathlib import Path
import cv2
import time

import numpy as np
# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, QProcess, pyqtSignal
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QFileDialog, QScrollArea, QWidget, QVBoxLayout, QLabel, QMessageBox
import sys
from PyQt5 import uic
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator

from config import Config

config_file_name = "config.json"


class ScrollLabel(QScrollArea):
    # constructor
    def __init__(self, *args, **kwargs):
        QScrollArea.__init__(self, *args, **kwargs)

        # making widget resizable
        self.setWidgetResizable(True)

        # making qwidget object
        content = QWidget(self)
        self.setWidget(content)

        # vertical box layout
        lay = QVBoxLayout(content)

        # creating label
        self.label = QLabel(content)

        # setting alignment to the text
        self.label.setAlignment(Qt.AlignLeft | Qt.AlignTop)

        # making label multi-line
        self.label.setWordWrap(True)

        # adding label to the layout
        lay.addWidget(self.label)

    # the setText method
    def setText(self, text):
        # setting text to the label
        self.label.setText(text)


class TraningThread(QThread):
    finished = pyqtSignal()  # Signal to indicate completion

    def __init__(self, config_data, yaml_file_path):
        super().__init__()
        self.config_data = config_data
        self.yaml_file_path = yaml_file_path

    def run(self):
        # try:
        model = YOLO(self.config_data.model_file_path)
        # model.to("cuda")
        results = model.train(data=self.yaml_file_path, imgsz=self.config_data.image_size,
                              workers=self.config_data.workers, epochs=self.config_data.epochs,
                              batch=self.config_data.batch, save_dir=self.config_data.config_path,
                              patience=self.config_data.patience, project=self.config_data.project)


class ImageWindow(QWidget):
    def __init__(self, qPixmapImage):
        super().__init__()
        self.label = QLabel(self)

        # Load the image
        self.pixmap = qPixmapImage  # Replace with your image path

        # Set up the layout
        layout = QVBoxLayout()
        layout.addWidget(self.label)
        self.setLayout(layout)

        # Display the image initially scaled to fit the window size
        self.update_image()

    def resizeEvent(self, event):
        # Update image size when window is resized
        self.update_image()

    def update_image(self):
        # Scale the image to the current window size while keeping aspect ratio
        self.label.setPixmap(self.pixmap.scaled(self.label.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation))


class Ui_MainWindow(object):
    def __init__(self):
        self.model = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 465)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lbImgPath = QtWidgets.QLabel(self.frame_4)
        self.lbImgPath.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lbImgPath.setFont(font)
        self.lbImgPath.setAutoFillBackground(False)
        self.lbImgPath.setStyleSheet("border-style: outset;\n"
                                     "font: 11pt \"MS Shell Dlg 2\";\n"
                                     "border-radius: 0px;\n"
                                     "border-width: 1px;\n"
                                     "border-color: white;\n"
                                     "color: rgb(255, 255, 255);")
        self.lbImgPath.setLineWidth(2)
        self.lbImgPath.setText("")
        self.lbImgPath.setObjectName("lbImgPath")
        self.horizontalLayout.addWidget(self.lbImgPath)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lbLabelPath = QtWidgets.QLabel(self.frame_7)
        self.lbLabelPath.setMaximumSize(QtCore.QSize(16777215, 28))
        self.lbLabelPath.setStyleSheet("border-style: outset;\n"
                                       "font: 11pt \"MS Shell Dlg 2\";\n"
                                       "border-radius: 0px;\n"
                                       "border-width: 1px;\n"
                                       "border-color: white;\n"
                                       "color: rgb(255, 255, 255);")
        self.lbLabelPath.setText("")
        self.lbLabelPath.setObjectName("lbLabelPath")
        self.horizontalLayout_2.addWidget(self.lbLabelPath)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lbModelPath = QtWidgets.QLabel(self.frame_6)
        self.lbModelPath.setMaximumSize(QtCore.QSize(16777215, 28))
        self.lbModelPath.setStyleSheet("border-style: outset;\n"
                                       "font: 11pt \"MS Shell Dlg 2\";\n"
                                       "border-radius: 0px;\n"
                                       "border-width: 1px;\n"
                                       "border-color: white;\n"
                                       "color: rgb(255, 255, 255);")
        self.lbModelPath.setText("")
        self.lbModelPath.setObjectName("lbModelPath")
        self.horizontalLayout_3.addWidget(self.lbModelPath)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lbConfigPath = QtWidgets.QLabel(self.frame_5)
        self.lbConfigPath.setMaximumSize(QtCore.QSize(16777215, 28))
        self.lbConfigPath.setStyleSheet("border-style: outset;\n"
                                        "font: 11pt \"MS Shell Dlg 2\";\n"
                                        "border-radius: 0px;\n"
                                        "border-width: 1px;\n"
                                        "border-color: white;\n"
                                        "color: rgb(255, 255, 255);")
        self.lbConfigPath.setText("")
        self.lbConfigPath.setObjectName("lbConfigPath")
        self.horizontalLayout_4.addWidget(self.lbConfigPath)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setStyleSheet("padding: 1px 20px 0px 0px;\n"
                                   "margin-left :20px")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rdbDetection = QtWidgets.QRadioButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rdbDetection.setFont(font)
        self.rdbDetection.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "padding: 1px 15px 1px 1px;")
        self.rdbDetection.setObjectName("rdbDetection")
        self.horizontalLayout_5.addWidget(self.rdbDetection)
        self.rdbSegmentation = QtWidgets.QRadioButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rdbSegmentation.setFont(font)
        self.rdbSegmentation.setStyleSheet("color: rgb(255, 255, 255);")
        self.rdbSegmentation.setObjectName("rdbSegmentation")
        self.horizontalLayout_5.addWidget(self.rdbSegmentation)
        self.rdbObbDetection = QtWidgets.QRadioButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rdbObbDetection.setFont(font)
        self.rdbObbDetection.setStyleSheet("color: rgb(255, 255, 255);")
        self.rdbObbDetection.setObjectName("rdbObbDetection")
        self.horizontalLayout_5.addWidget(self.rdbObbDetection)
        self.rdbClassification = QtWidgets.QRadioButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rdbClassification.setFont(font)
        self.rdbClassification.setStyleSheet("color: rgb(255, 255, 255);")
        self.rdbClassification.setObjectName("rdbClassification")
        self.horizontalLayout_5.addWidget(self.rdbClassification)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.txtEpochs = QtWidgets.QTextEdit(self.frame_10)
        self.txtEpochs.setMaximumSize(QtCore.QSize(100, 50))
        self.txtEpochs.setStyleSheet("height : 35px;\n"
                                     "font: 11pt \"MS Shell Dlg 2\";\n"
                                     "color: rgb(255, 255, 255);")
        self.txtEpochs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtEpochs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtEpochs.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtEpochs.setMarkdown("")
        self.txtEpochs.setObjectName("txtEpochs")
        self.horizontalLayout_6.addWidget(self.txtEpochs)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.spinImgSz = QtWidgets.QSpinBox(self.frame_10)
        self.spinImgSz.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinImgSz.setFont(font)
        self.spinImgSz.setStyleSheet("height :100%;\n"
                                     "color: rgb(255, 255, 255);")
        self.spinImgSz.setAlignment(QtCore.Qt.AlignCenter)
        self.spinImgSz.setMinimum(416)
        self.spinImgSz.setMaximum(1280)
        self.spinImgSz.setSingleStep(32)
        self.spinImgSz.setProperty("value", 640)
        self.spinImgSz.setObjectName("spinImgSz")
        self.horizontalLayout_6.addWidget(self.spinImgSz)
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.spinWorkers = QtWidgets.QSpinBox(self.frame_10)
        self.spinWorkers.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinWorkers.setFont(font)
        self.spinWorkers.setStyleSheet("height : 100%;\n"
                                       "color: rgb(255, 255, 255);")
        self.spinWorkers.setAlignment(QtCore.Qt.AlignCenter)
        self.spinWorkers.setMinimum(1)
        self.spinWorkers.setMaximum(10)
        self.spinWorkers.setObjectName("spinWorkers")
        self.horizontalLayout_6.addWidget(self.spinWorkers)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.txtBatch = QtWidgets.QTextEdit(self.frame_11)
        self.txtBatch.setMaximumSize(QtCore.QSize(100, 100))
        self.txtBatch.setStyleSheet("height : 45px;\n"
                                    "font: 11pt \"MS Shell Dlg 2\";\n"
                                    "color: rgb(255, 255, 255);")
        self.txtBatch.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtBatch.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtBatch.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtBatch.setMarkdown("")
        self.txtBatch.setObjectName("txtBatch")
        self.horizontalLayout_8.addWidget(self.txtBatch)
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        self.label_9.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.txtPatience = QtWidgets.QTextEdit(self.frame_11)
        self.txtPatience.setMaximumSize(QtCore.QSize(100, 100))
        self.txtPatience.setStyleSheet("height : 45px;\n"
                                       "font: 11pt \"MS Shell Dlg 2\";\n"
                                       "color: rgb(255, 255, 255);")
        self.txtPatience.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPatience.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPatience.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtPatience.setMarkdown("")
        self.txtPatience.setObjectName("txtPatience")
        self.horizontalLayout_8.addWidget(self.txtPatience)
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.txtProject = QtWidgets.QTextEdit(self.frame_11)
        self.txtProject.setMaximumSize(QtCore.QSize(100, 100))
        self.txtProject.setStyleSheet("height : 45px;\n"
                                      "font: 11pt \"MS Shell Dlg 2\";\n"
                                      "color: rgb(255, 255, 255);")
        self.txtProject.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtProject.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtProject.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtProject.setMarkdown("")
        self.txtProject.setObjectName("txtProject")
        self.horizontalLayout_8.addWidget(self.txtProject)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnStartTrain = QtWidgets.QPushButton(self.frame_9)
        self.btnStartTrain.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnStartTrain.setFont(font)
        self.btnStartTrain.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(203, 203, 203);\n"
                                         "background-color: rgb(127, 127, 127);\n"
                                         "border: 2px solid gray;\n"
                                         "border-radius: 10px;\n"
                                         "height : 50px;\n"
                                         "margin : 0px 10px 0px 10px")
        self.btnStartTrain.setObjectName("btnStartTrain")
        self.horizontalLayout_7.addWidget(self.btnStartTrain)
        self.btnTest = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnTest.setFont(font)
        self.btnTest.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(203, 203, 203);\n"
                                   "background-color: rgb(127, 127, 127);\n"
                                   "border: 2px solid gray;\n"
                                   "border-radius: 10px;\n"
                                   "height : 50px;\n"
                                   "margin : 0px 10px 0px 10px")
        self.btnTest.setObjectName("btnTest")
        self.horizontalLayout_7.addWidget(self.btnTest)
        self.btnAutoLabel = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAutoLabel.setFont(font)
        self.btnAutoLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(203, 203, 203);\n"
                                        "background-color: rgb(127, 127, 127);\n"
                                        "border: 2px solid gray;\n"
                                        "border-radius: 10px;\n"
                                        "height : 50px;\n"
                                        "margin : 0px 10px 0px 10px")
        self.btnAutoLabel.setObjectName("btnAutoLabel")
        self.horizontalLayout_7.addWidget(self.btnAutoLabel)
        self.btnConvertOnnx = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnConvertOnnx.setFont(font)
        self.btnConvertOnnx.setStyleSheet("color: rgb(255, 255, 255);\n"
                                          "background-color: rgb(203, 203, 203);\n"
                                          "background-color: rgb(127, 127, 127);\n"
                                          "border: 2px solid gray;\n"
                                          "border-radius: 10px;\n"
                                          "height : 50px;\n"
                                          "margin : 0px 10px 0px 10px")
        self.btnConvertOnnx.setObjectName("btnConvertOnnx")
        self.horizontalLayout_7.addWidget(self.btnConvertOnnx)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YoloV8 Training"))
        self.label_2.setText(_translate("MainWindow", "Images Path"))
        self.label_3.setText(_translate("MainWindow", "Labels Path"))
        self.label_4.setText(_translate("MainWindow", "Model Path"))
        self.label_8.setText(_translate("MainWindow", "Config Path"))
        self.rdbDetection.setText(_translate("MainWindow", "Detection"))
        self.rdbSegmentation.setText(_translate("MainWindow", "Segmentation"))
        self.rdbObbDetection.setText(_translate("MainWindow", "ObbDetection"))
        self.rdbClassification.setText(_translate("MainWindow", "Classification"))
        self.label_6.setText(_translate("MainWindow", "Epochs"))
        self.label_10.setText(_translate("MainWindow", "Image Size"))
        self.label_5.setText(_translate("MainWindow", "Workers"))
        self.label_7.setText(_translate("MainWindow", "Batch"))
        self.label_9.setText(_translate("MainWindow", "Patience"))
        self.label_11.setText(_translate("MainWindow", "Project"))
        self.btnStartTrain.setText(_translate("MainWindow", "TRAIN"))
        self.btnTest.setText(_translate("MainWindow", "TEST"))
        self.btnAutoLabel.setText(_translate("MainWindow", "AUTO LABEL"))
        self.btnConvertOnnx.setText(_translate("MainWindow", "CONVERT ONNX"))
        self.txtEpochs.setText("2000")
        self.txtBatch.setText("16")
        self.txtPatience.setText("100")
        self.rdbDetection.setChecked(True)

        self.lbImgPath.mousePressEvent = self.onImageLabelClick
        self.lbModelPath.mousePressEvent = self.onModelFileSelect
        self.lbLabelPath.mousePressEvent = self.onLabelPathClick
        self.lbConfigPath.mousePressEvent = self.onConfigPathClick
        # Event cho button
        self.btnStartTrain.clicked.connect(self.onButtonStartTrainClick)
        self.btnTest.clicked.connect(self.onButtonTestClick)
        self.btnAutoLabel.clicked.connect(self.onAutoLabelClick)
        self.btnConvertOnnx.clicked.connect(self.onConvertOnnxClick)

        self.config_data = self.load_config_file(config_file_name)
        self.lbImgPath.setText(self.config_data.image_path)
        self.lbConfigPath.setText(self.config_data.config_path)
        self.lbLabelPath.setText(self.config_data.label_path)
        self.lbModelPath.setText(self.config_data.model_file_path)
        self.txtEpochs.setText(str(self.config_data.epochs))
        self.spinWorkers.setValue(self.config_data.workers)
        self.txtPatience.setText(str(self.config_data.patience))
        self.txtBatch.setText(str(self.config_data.batch))
        self.txtProject.setText(str(self.config_data.project))

    def onConvertOnnxClick(self, event):
        if not self.lbModelPath.text().strip():
            QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng chọn model file")
            return
        try:
            self.btnConvertOnnx.setText("Converting...")
            model = YOLO(self.lbModelPath.text())
            model.export(format="onnx")
            QMessageBox.warning(MainWindow, "Thông báo", "Hoàn thành convert")
            self.btnConvertOnnx.setText("CONVERT ONNX")
        except:
            QMessageBox.warning(MainWindow, "Thông báo", "Convert Onnx Exception")

    def onAutoLabelClick(self, event):
        folder_image_path = QFileDialog.getExistingDirectory(None, "Select Image Folder")
        if folder_image_path:
            self.detect_annotator(folder_image_path, folder_image_path, self.config_data.model_file_path)
        else:
            print("No folder selected")

    def onButtonTestClick(self, event):
        if not self.lbModelPath.text().strip():
            QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng chọn model file")
            return
        image_path, _ = QFileDialog.getOpenFileName(caption="Open Pre-train Model", filter="*.jpg *.bmp *.png")

        if image_path:
            if self.model is None:
                self.model = YOLO(self.config_data.model_file_path)
            frame_mat = cv2.imread(image_path)
            if self.rdbDetection.isChecked():
                time_start = time.perf_counter()

                results = self.model.predict(frame_mat, imgsz=self.config_data.image_size, verbose=False)
                time_end = (time.perf_counter() - time_start) * 1000.0
                file_name = os.path.basename(image_path)
                print(f"Frame {file_name} : {time_end:.2f} ms")

                for r in results:  # mỗi r tương ứng với 1 ảnh
                    for box in r.boxes:
                        conf = box.conf.item()  # độ tin cậy (float)
                        cls = int(box.cls.item())  # class ID
                        name = r.names[cls]
                        print(f"{name}, Confidence: {conf:.2f}")

                img = results[0].plot()  # This plots the detections on the image
                img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                height, width, channel = img_rgb.shape
                bytes_per_line = 3 * width
                q_image = QPixmap.fromImage(QImage(img_rgb.data, width, height, bytes_per_line, QImage.Format_RGB888))
                self.image_window = ImageWindow(q_image)
                self.image_window.setWindowTitle("Image Window")
                self.image_window.setGeometry(100, 100, 800, 600)
                self.image_window.show()

            if self.rdbClassification.isChecked():
                time_start = time.perf_counter()

                results = self.model.predict(frame_mat, imgsz=224, verbose=False)[0]
                time_end = (time.perf_counter() - time_start) * 1000.0
                probs = results.probs
                # lấy chỉ số và tên class top-1
                top1 = probs.top1
                top1_name = self.model.names[top1]
                top1_score = float(probs.data[top1])
                file_name = os.path.basename(image_path)
                print(f"{file_name} -> {top1_name} ({top1_score:.2f}) {time_end:.2f} ms")
                #

                img_rgb = cv2.cvtColor(frame_mat, cv2.COLOR_BGR2RGB)

                # Vẽ text lên ảnh (góc trên bên trái)
                text = f"{top1_name} ({top1_score * 100:.2f}%)"
                font = cv2.FONT_HERSHEY_SIMPLEX
                cv2.putText(img_rgb, text, (20, 40), font, 1.0, (0, 255, 0), 1, cv2.LINE_AA)

                height, width, channel = img_rgb.shape
                bytes_per_line = 3 * width
                #
                # #cv2.putText(img_rgb,top1_name,(255, 255, 255), 1, cv2.LINE_AA)
                q_image = QPixmap.fromImage(QImage(img_rgb.data, width, height, bytes_per_line, QImage.Format_RGB888))
                self.image_window = ImageWindow(q_image)
                self.image_window.setWindowTitle("Image Window")
                self.image_window.setGeometry(100, 100, 800, 600)
                self.image_window.show()

    def onImageLabelClick(self, event):
        folder_image_path = QFileDialog.getExistingDirectory(None, "Select Folder")
        if folder_image_path:
            self.lbImgPath.setText(folder_image_path)
            self.config_data.image_path = folder_image_path
            self.save_config_file(self.config_data, config_file_name)
        else:
            print("No folder selected")

    def onLabelPathClick(self, event):
        folder_label_path = QFileDialog.getExistingDirectory(None, "Select Folder")
        if folder_label_path:
            self.lbLabelPath.setText(folder_label_path)
            self.config_data.label_path = folder_label_path
            self.save_config_file(self.config_data, config_file_name)
        else:
            print("No folder selected")

    def onModelFileSelect(self, event):
        model_file_path, _ = QFileDialog.getOpenFileName(caption="Open Pre-train Model", filter="*.pt *.onnx")
        if model_file_path:
            self.lbModelPath.setText(model_file_path)
            self.model = YOLO(model_file_path)
            self.config_data.model_file_path = model_file_path
            self.save_config_file(self.config_data, config_file_name)

    def onConfigPathClick(self, event):
        folder_config_path = QFileDialog.getExistingDirectory(None, "Select Folder")
        if folder_config_path:
            self.lbConfigPath.setText(folder_config_path)
            self.config_data.config_path = folder_config_path
            self.save_config_file(self.config_data, config_file_name)
        else:
            print("No folder selected")

    def onButtonStartTrainClick(self, event):
        text = self.btnStartTrain.text()
        if text == "TRAIN":
            if not self.lbImgPath.text().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng chọn thư mục ảnh")
                return
            if not self.lbLabelPath.text().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng chọn thư mục label")
                return
            if not self.lbConfigPath.text().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng chọn thư mục lưu config")
                return
            if not self.lbModelPath.text().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng chọn model file")
                return
            if not self.txtEpochs.toPlainText().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng nhập số epoch")
                return
            if not self.txtBatch.toPlainText().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng nhập số batch")
                return
            if not self.txtPatience.toPlainText().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng nhập số patience")
                return
            if not self.txtProject.toPlainText().strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Vui lòng nhập tên prject")
                return
            self.config_data.config_path = self.lbConfigPath.text()
            self.config_data.label_path = self.lbLabelPath.text()
            self.config_data.model_file_path = self.lbModelPath.text()
            self.config_data.image_path = self.lbImgPath.text()
            self.config_data.epochs = int(self.txtEpochs.toPlainText())
            self.config_data.image_size = int(self.spinImgSz.value())
            self.config_data.workers = int(self.spinWorkers.value())
            self.config_data.batch = int(self.txtBatch.toPlainText())
            self.config_data.patience = int(self.txtPatience.toPlainText())
            self.config_data.project = self.txtProject.toPlainText()

            self.copyImageToFolder()
            yaml_file_path = self.createXamlFile()

            if not yaml_file_path.strip():
                QMessageBox.warning(MainWindow, "Thông báo", "Lỗi tạo file xaml")
                return

            self.save_config_file(self.config_data, config_file_name)
            self.train_thread = TraningThread(self.config_data, yaml_file_path=yaml_file_path)
            self.train_thread.finished.connect(self.on_training_finished)
            self.train_thread.start()
            self.btnStartTrain.setText("STOP")
        else:
            self.btnStartTrain.setText("TRAIN")

    def on_training_finished(self):
        # Thông báo khi huấn luyện hoàn tất
        QMessageBox.information(self, "Thông báo", "Huấn luyện đã hoàn tất!")
        self.btnStartTrain.setEnabled(True)  # Kích hoạt lại nút bấm

    def detect_annotator(self,
                         data: str = 'datasets/images',
                         output_dir: str = 'output',
                         det_model: str = 'datasets/best_X6hs.pt',
                         used_device: dict = 'CPU'
                         ):

        # Load the YOLO model
        det_model = YOLO(det_model)

        # Set the datasets path and output directory
        data_path = Path(data)
        if not output_dir:
            output_dir = data_path.parent / 'output'

        os.makedirs(
            output_dir,
            exist_ok=True
        )

        # Run the model on the datasets
        det_results = det_model(
            data_path,
            stream=True,
            device=used_device
        )

        # Iterate over the detection results
        for result in det_results:
            # Get the class IDs and bounding boxes
            class_ids = result.boxes.cls.int().tolist()
            boxes = result.boxes.xywhn

            # Get the image filename and create the annotation filename
            img_filename = os.path.splitext(os.path.basename(result.path))[0]
            ann_filename = img_filename + '.txt'

            # If there are detections, write them to the annotation file
            if len(class_ids):
                with open(os.path.join(output_dir, ann_filename), 'w') as f:
                    for class_id, box in zip(class_ids, boxes):
                        box = map(str, box.tolist())
                        f.write(f'{class_id} ' + ' '.join(box) + '\n')
        QMessageBox.information(self, "Thông báo", "Auto Label đã hoàn tất!")

    def load_config_file(self, file_path):
        # Read the JSON file and convert it back to a dictionary
        if not os.path.isfile(file_path):
            config_data = Config("", "", "", "", 2000, 640, 1, 16, 100, "")
            self.save_config_file(config_data, config_file_name)
            return
        try:
            with open(file_path, 'r', encoding='utf-8') as file:
                config_info_data_read = json.load(file)
            # Create an instance of Person from the dictionary
            config_info_class = Config.from_dict(config_info_data_read)
            return config_info_class
        except:
            return None

    def copyImageToFolder(self):
        # images = [f for f in os.listdir(self.config_data.image_path) if
        #           os.path.isfile(os.path.join(self.config_data.image_path, f))]

        images = self.get_all_images(self.config_data.image_path)
        image_train_path = os.path.join(self.config_data.config_path, "data/train/images")
        image_val_path = os.path.join(self.config_data.config_path, "data/val/images")
        label_train_path = os.path.join(self.config_data.config_path, "data/train/labels")
        label_val_path = os.path.join(self.config_data.config_path, "data/val/labels")
        if not os.path.exists(image_train_path):
            os.makedirs(image_train_path)
        if not os.path.exists(image_val_path):
            os.makedirs(image_val_path)
        if not os.path.exists(label_train_path):
            os.makedirs(label_train_path)
        if not os.path.exists(label_val_path):
            os.makedirs(label_val_path)

        index = 0
        for image in images:

            new_image_folder = image_train_path
            new_label_folder = label_train_path
            if index == 4:
                new_image_folder = image_val_path
                new_label_folder = label_val_path
            old_image_path = os.path.join(self.config_data.image_path, image)
            image_path_base = os.path.basename(image)
            new_image_path = os.path.join(new_image_folder, image_path_base)
            old_label_path = os.path.join(self.config_data.label_path, os.path.splitext(image)[0] + ".txt")
            label_path_base = os.path.basename(os.path.splitext(image)[0] + ".txt")
            new_label_path = os.path.join(new_label_folder, label_path_base)
            if not os.path.isfile(old_label_path):
                continue

            shutil.copy(old_image_path, new_image_path)
            shutil.copy(old_label_path, new_label_path)
            index = index + 1
            if index == 5:
                index = 0

    def get_all_images(self, folder_path):

        filter_extensions = {".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".webp"}
        image_files = []

        for root, _, files in os.walk(folder_path):
            for filename in files:
                if any(filename.lower().endswith(ext) for ext in filter_extensions):
                    relative_path = os.path.relpath(os.path.join(root, filename), folder_path)
                    image_files.append(relative_path)
        return image_files

    def save_config_file(self, config_info_class, config_file_path):
        # Convert the Person instance to a dictionary
        config_info_data = config_info_class.to_dict()
        # Write the dictionary to a JSON file
        with open(config_file_path, 'w', encoding="utf-8") as file:
            json.dump(config_info_data, file, ensure_ascii=False, indent=4)

    def show_message(self, title, text, icon_type=QMessageBox.Information, buttons=QMessageBox.Ok):
        msg_box = QMessageBox()
        msg_box.setWindowTitle(title)
        msg_box.setText(text)
        msg_box.setIcon(icon_type)
        msg_box.setStandardButtons(buttons)
        # Execute the message box and get the result
        result = msg_box.exec_()
        return result

    # def copyImageToFolder(self):
    #     # images = [f for f in os.listdir(self.config_data.image_path) if
    #     #           os.path.isfile(os.path.join(self.config_data.image_path, f))]
    #
    #     images = self.get_image_file(self.config_data.image_path)
    #     image_train_path = os.path.join(self.config_data.config_path, "train_data/train/images")
    #     image_val_path = os.path.join(self.config_data.config_path, "train_data/val/images")
    #     label_train_path = os.path.join(self.config_data.config_path, "train_data/train/labels")
    #     label_val_path = os.path.join(self.config_data.config_path, "train_data/val/labels")
    #     if not os.path.exists(image_train_path):
    #         os.makedirs(image_train_path)
    #     if not os.path.exists(image_val_path):
    #         os.makedirs(image_val_path)
    #     if not os.path.exists(label_train_path):
    #         os.makedirs(label_train_path)
    #     if not os.path.exists(label_val_path):
    #         os.makedirs(label_val_path)
    #
    #     index = 0
    #     for image in images:
    #
    #         new_image_folder = image_train_path
    #         new_label_folder = label_train_path
    #         if index == 4:
    #             new_image_folder = image_val_path
    #             new_label_folder = label_val_path
    #         old_image_path = os.path.join(self.config_data.image_path, image)
    #         new_image_path = os.path.join(new_image_folder, image)
    #         old_label_path = os.path.join(self.config_data.label_path, os.path.splitext(image)[0] + ".txt")
    #         new_label_path = os.path.join(new_label_folder, os.path.splitext(image)[0] + ".txt")
    #         if not os.path.isfile(old_label_path):
    #             continue
    #
    #         shutil.copy(old_image_path, new_image_path)
    #         shutil.copy(old_label_path, new_label_path)
    #         index = index + 1
    #         if index == 5:
    #             index = 0
    # def get_image_file(self,folder_path):
    #     # Các định dạng file ảnh
    #     filter = ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff']
    #     files = []
    #
    #     for filename in os.listdir(folder_path):
    #         if any(filename.lower().endswith(dinh_dang) for dinh_dang in filter):
    #             files.append(filename)
    #
    #     return files
    def createXamlFile(self):
        if self.rdbDetection.isChecked():

            class_file_path = os.path.join(self.config_data.label_path, "classes.txt")
            if not os.path.exists(class_file_path):
                QMessageBox.warning('Thông báo', "File classes.txt không tồn tại\r\n"
                                                  "Copy file classes.txt vào thư mục label")
            f = open(class_file_path, "r")

            with open(class_file_path) as file_in:
                lines = []
                for line in file_in:
                    lines.append(line.replace("\r", "").replace("\n", ""))

            # datasets = f.read()
            for name in lines:
                print(name)
            config_file_path = os.path.join(self.config_data.config_path, "detection_screw.yaml")
            f = open(config_file_path, "w")
            f.write("train: " + self.config_data.config_path + "/train_data/train\n" +
                    "val: " + self.config_data.config_path + "/train_data/val\n" +
                    "nc : " + str(lines.__len__()) + "\n" +
                    "names: " + str(lines))
            return config_file_path
        else:
            return ""


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet("""
        QMessageBox {
        background-color: #f0f0f0;
        }
        QMessageBox QLabel {
        color: rgb(200, 200, 200);
        background-color: rgb(255, 255, 255);
        font-size : 12pt;
        }
    """)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
